# Generated by Django 5.1.6 on 2025-04-20 10:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Removed auth dependency - using Supabase authentication only
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("groww", "Groww"),
                            ("zerodha", "Zerodha"),
                            ("upstox", "Upstox"),
                            ("dhan", "Dhan"),
                            ("5paisa", "5Paisa"),
                            ("angel", "Angel One"),
                            ("icici", "ICICI Direct"),
                            ("other", "Other"),
                        ],
                        default="groww",
                        max_length=20,
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("NSE", "National Stock Exchange"),
                            ("BSE", "Bombay Stock Exchange"),
                        ],
                        default="NSE",
                        max_length=3,
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[
                            ("equity-delivery", "Equity Delivery"),
                            ("equity-intraday", "Equity Intraday"),
                            ("futures", "Futures"),
                            ("options", "Options"),
                        ],
                        default="equity-delivery",
                        max_length=20,
                    ),
                ),
                ("total_quantity", models.PositiveIntegerField(default=0)),
                (
                    "total_buy_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "total_sell_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "average_buy_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "gross_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "net_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                # Removed user foreign key - using Supabase UUID instead
            ],
        ),
        migrations.CreateModel(
            name="TransactionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("groww", "Groww"),
                            ("zerodha", "Zerodha"),
                            ("upstox", "Upstox"),
                            ("dhan", "Dhan"),
                            ("5paisa", "5Paisa"),
                            ("angel", "Angel One"),
                            ("icici", "ICICI Direct"),
                            ("other", "Other"),
                        ],
                        default="groww",
                        max_length=20,
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("NSE", "National Stock Exchange"),
                            ("BSE", "Bombay Stock Exchange"),
                        ],
                        default="NSE",
                        max_length=3,
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[
                            ("equity-delivery", "Equity Delivery"),
                            ("equity-intraday", "Equity Intraday"),
                            ("futures", "Futures"),
                            ("options", "Options"),
                        ],
                        default="equity-delivery",
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("buy_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sell_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("buy_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("sell_value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_brokerage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "stt",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "exchange_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "stamp_duty",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "sebi_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "ipft",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("gross_pnl", models.DecimalField(decimal_places=2, max_digits=12)),
                ("net_pnl", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="calculator.transactiongroup",
                    ),
                ),
                # Removed user foreign key - using Supabase UUID instead
            ],
        ),
    ]
