# Generated by Django 5.1.6 on 2025-07-06 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionrecord",
            name="group",
        ),
        migrations.DeleteModel(
            name="TransactionGroup",
        ),
        migrations.DeleteModel(
            name="TransactionRecord",
        ),
    ]
