# Generated by Django 5.1.6 on 2025-07-09 12:32
# + Create model AuthenticationAttempt
# + Create model TokenBlacklist

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calculator", "0002_remove_transactionrecord_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("success", models.BooleanField(default=False)),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invalid_token", "Invalid token"),
                            ("expired_token", "Expired token"),
                            ("blacklisted_token", "Blacklisted token"),
                            ("malformed_token", "Malformed token"),
                            ("missing_claims", "Missing required claims"),
                            ("invalid_signature", "Invalid signature"),
                            ("configuration_error", "Configuration error"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("token_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Authentication Attempt",
                "verbose_name_plural": "Authentication Attempts",
                "db_table": "auth_authentication_attempt",
                "indexes": [
                    models.Index(
                        fields=["user_id", "attempted_at"],
                        name="auth_authen_user_id_981a9d_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "attempted_at"],
                        name="auth_authen_ip_addr_07efa7_idx",
                    ),
                    models.Index(
                        fields=["success", "attempted_at"],
                        name="auth_authen_success_1e6e14_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TokenBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                (
                    "issued_at",
                    models.DateTimeField(
                        help_text="When the token was originally issued"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the token expires"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the token was revoked",
                    ),
                ),
                (
                    "revocation_reason",
                    models.CharField(
                        choices=[
                            ("logout", "User logout"),
                            ("password_change", "Password changed"),
                            ("security_breach", "Security breach"),
                            ("admin_revoke", "Admin revocation"),
                            ("suspicious_activity", "Suspicious activity detected"),
                            ("token_refresh", "Token refreshed"),
                        ],
                        default="logout",
                        max_length=100,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Blacklisted Token",
                "verbose_name_plural": "Blacklisted Tokens",
                "db_table": "auth_token_blacklist",
                "indexes": [
                    models.Index(
                        fields=["token_hash"], name="auth_token__token_h_f5fbba_idx"
                    ),
                    models.Index(
                        fields=["user_id", "revoked_at"],
                        name="auth_token__user_id_7ae71e_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="auth_token__expires_e93997_idx"
                    ),
                ],
            },
        ),
    ]
