# Generated by Django 5.1.6 on 2025-07-17 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthenticationAttempt",
        ),
        migrations.DeleteModel(
            name="TokenBlacklist",
        ),
    ]
