# Generated by Django 5.1.6 on 2025-06-06 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Removed auth dependency - using Supabase authentication only
    ]

    operations = [
        migrations.CreateModel(
            name="TradeJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[
                            ("EQUITY_DELIVERY", "Equity Delivery"),
                            ("EQUITY_INTRADAY", "Equity Intraday"),
                            ("ETF", "ETF"),
                            ("FUTURES", "Futures"),
                            ("OPTIONS", "Options"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("buy_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sell_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("entry_date", models.DateField()),
                ("exit_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED_TARGET", "Closed - Target"),
                            ("CLOSED_STOPLOSS", "Closed - Stoploss"),
                            ("CLOSED_MANUAL", "Closed - Manual"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("personal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                # Removed user foreign key - using Supabase UUID instead
                ("direction", models.CharField(choices=[("LONG", "Long"), ("SHORT", "Short")], default="LONG", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="TradeTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                # Removed user foreign key - using Supabase UUID instead
            ],
        ),
        migrations.CreateModel(
            name="TradeJournalTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal.tradejournal",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal.tradetags",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tradejournal",
            name="tags",
            field=models.ManyToManyField(
                related_name="journals",
                through="journal.TradeJournalTags",
                to="journal.tradetags",
            ),
        ),
    ]
