# Generated by Django 5.1.6 on 2025-06-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='tradejournal',
            name='direction',
            field=models.CharField(
                max_length=10,
                choices=[('LONG', 'Long'), ('SHORT', 'Short')],
                default='LONG',
            ),
        ),
    ]
