# Generated by Django 5.1.6 on 2025-06-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_auto_20250608_2223"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradejournal",
            name="broker",
            field=models.CharField(
                choices=[
                    ("Dhan", "Dhan"),
                    ("Groww", "Groww"),
                    ("Rise", "Rise"),
                    ("Others", "Others"),
                ],
                default="Groww",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tradejournal",
            name="exchange",
            field=models.CharField(
                choices=[("NSE", "NSE"), ("BSE", "BSE")], default="NSE", max_length=10
            ),
        ),
    ]
