# Generated by Django 5.1.6 on 2025-07-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0006_recover_user_trade_associations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradejournal",
            name="broker",
            field=models.CharField(
                choices=[("Dhan", "Dhan"), ("Groww", "Groww")],
                default="Dhan",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tradejournal",
            name="trade_type",
            field=models.CharField(
                choices=[
                    ("EQUITY_DELIVERY", "Equity Delivery"),
                    ("EQUITY_INTRADAY", "Equity Intraday"),
                ],
                max_length=20,
            ),
        ),
    ]
