# Generated by Django 5.1.6 on 2025-07-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0007_alter_tradejournal_broker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradejournal",
            name="buy_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
